# Generated by Django 4.2.3 on 2023-08-28 11:41
from django.db import migrations
import environ

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_issue_assigned_to'),
    ]   

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        env = environ.Env(
            DEBUG=(bool, True)
        )
        environ.Env.read_env()

        DJANGO_SU_NAME = env('DJANGO_SU_NAME')
        DJANGO_SU_EMAIL = env('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = env('DJANGO_SU_PASSWORD')

        superuser = User.objects.create_superuser(username=DJANGO_SU_NAME, email=DJANGO_SU_EMAIL, password=DJANGO_SU_PASSWORD)
        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
