# Generated by Django 4.2.3 on 2023-08-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_issue_assigned_to'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@company.com',
            password='pass12345')

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
